version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: notes-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=notesdb
      - SECRET_KEY=change-me
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  frontend:
    image: node:18
    container_name: notes-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    command: sh -c "npm install --silent && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

volumes:
  mongo-data:
